#!/bin/sh
VERSION=7.8.0

echo "- copy source"
cp -a src src_tarball
cd src_tarball

#echo "- remove unwanted"
#rm -rf freetype-2.1.10
#rm -rf libpng-1.2.32
#rm -rf SDL-1.2.13
#rm -rf SDL_gfx-2.0.15
#rm -rf SDL_image-1.2.5
#rm -rf SDL_ttf-2.0.8

echo "- remove .git"
find . -name .git -exec rm -rf {} \;

cd ..

echo "- link to as dir"
ln -sf src_tarball squeezeplay-$VERSION

echo "- doing tarball"
tar cfhj squeezeplay-$VERSION.tar.bz2 squeezeplay-$VERSION

echo "- cleaning dir"
rm -rf src_tarball squeezeplay-$VERSION
